### ISSUE TITLE
Mencionar este projeto no site do VRaptor

### ISSUE THREAD

**Issue by danilomunoz** [caelum/vraptor-java8#15]
Pessoal, 

O que acham de adicionar um link para este projeto na página de documentação do VRaptor onde se fala sobre JDK 7 e 8?

**Comment by Turini** [comment]
oi @danilomunoz; a gente menciona ele na página de plugins: 
http://www.vraptor.org/en/docs/plugins/#vraptor-java-8

mas se achar algum lugar que sentiu falta, podemos adicionar sim, sem dúvida.

**Comment by danilomunoz** [comment]
Valeu @Turini !

Eu mesmo não entrei na área de plugins, fui diretamente para dependências e pré-requisitos:
- http://www.vraptor.org/en/docs/dependencies-and-prerequisites/#dependencies-and-prerequisites - VRaptor 4 depends directly on CDI 1.1, so it will work only in servers that support this version of CDI, or higher like CDI 1.2. **JDK 1.7 or higher is also mandatory**.
- http://www.vraptor.org/en/docs/dependencies-and-prerequisites/#jdk-8 - não menciona o plugin e fala somente do **javassist**.

Obrigado.

**Comment by Turini** [comment]
bem observado, @danilomunoz 

seria uma boa adicionar lá sim! você quer tentar nos mandar um pull-request?

se não der, abre essa issue lá no repo do vraptor4?

**Comment by danilomunoz** [comment]
Feito... espero que fique bom...

**Comment by Turini** [comment]
ficou ótimo! deixei uma sugestão lá, assim que vc der sua opinião eu já faço merge

valeu!

**Comment by Turini** [comment]
closed by https://github.com/caelum/vraptor4/pull/1066
